import './globals.css';
import type { Metadata } from 'next';
import { Bitter, Italianno } from 'next/font/google';

const bitter = Bitter({ subsets: ['latin'] });

const ita = Italianno({ subsets: ['latin'], weight: ['400'] });

export const metadata: Metadata = {
	title: 'Aniversário da Clarice',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='pt-BR'>
			<link
				rel='shortcut icon'
				href='/favicon.png'
				type='image/x-icon'
			/>
			<body className={`${bitter.className} ${ita.className}`}>{children}</body>
		</html>
	);
}
